### ISSUE TITLE
Encode/Decode definition object

### ISSUE THREAD

**Issue by DaTeL237** [noties/SharedPreferencesGenerator#3]
It would be useful if the generated class has functions to generate a class of the definition type, and vice versa.

My use case is a live wallpaper that uses SharedPreferences to define the current appearance. I store a set of settings in a database/file as presets. Multiple presets are available so they will be deserialized from DB/file and then should be set to the an instance of SharedPreferences.
Using the Simplest example, I would be decorating the Simplest class with annotations that allow another library to do the persistence to/from DB or file. Easy conversion between Simplest and SimplestPreferences would thus be useful.

ps Let me know if you feel like adding support for this, Alternatively I may work on it myself.

**Comment by noties** [comment]
Hi!

It's a very interesting idea. And I somehow missed this use-case when I was developing this library. I thought that for example `Simplest` would be used only to define a schema of SharedPreferences (and then it could be painlessly removed from the project via ProGuard or whatever). And would not be used anywhere else. I didn't think that this `Simplest` object would be stored somewhere else (well, because SharedPreferences is a storage already). 

I'm afraid that adding this feature would harm the flexibility of managing ones objects (handing nulls, zeros, special cases). And it kind of kills the idea of an object that always has the latest changes... 

As a possible solution I would recommend writing factory methods that would set the values & generate the class. 

[OFFTOP] Isn't it easier to store an id/fileName of your setting in the SharedPreferenes and not store it again just in another storage?

**Comment by DaTeL237** [comment]
Thanks for your feedback noties. At the moment I've indeed got straightforward methods to create the definition object.

I'd say the last suggestion isn't offtopic :) I didn't really think about using multiple SharedPreference names... even though I used it in other projects :D I'm defining (some of) the settings at compile time though, so as far as I'm aware I cannot ship those as SharedPreferences that can be read on the device

Knowing your perspective I'd say the issue can be closed
